pipeline:
  build:
    image: 'karrug/dsin100dayscicd:0.1'
    pull: true
    commands:
      - /root/env/bin/python tools/buildhtmlpages.py
    branch: master
    when:
      event: push

  deploy:
    image: 'druuu/dsin100days:0.3'
    pull: true
    commands:
      - pwd
      - ls
    when:
      event: tag
