pipeline:
  build:
    image: 'karrug/dsin100dayscicd:0.1'
    pull: true
    commands:
      - pwd
      - ls
    branch: master
    when:
      event: push

  deploy:
    image: 'druuu/dsin100days:0.3'
    pull: true
    commands:
      - true
    when:
      event: tag
