pipeline:
    deploy:
        image: druuu/dsin100days:0.1
        pull: true
        commands:
            - ls
            - echo '>>>>>>> copying.. <<<<<<<<<<<'
            - echo ${DRONE_TAG}
            - s3cmd --access_key=$${ACCESS_KEY} --secret_key=$${SECRET_KEY} sync --recursive . s3://$${BUCKET_NAME}/dsin100days/
            - echo '>>>>>>> copied <<<<<<<<<<<'
        secrets: [ access_key, secret_key ]
        when:
            event: [push, tag]
