pipeline:
  build:
    image: 'karrug/dsin100dayscicd:0.2'
    commands:
      - /root/env/bin/python tools/buildhtmlpages.py
    when:
      event: [push, pull_request, tag, deployment]

  deploy:
    image: 'druuu/dsin100days:0.3'
    commands:
      - pwd
      - ls
    when:
      event: tag
